sudo: true
language: java
cache:
  directories:
    - $HOME/.m2
services:
    - postgresql
addons:
  postgresql: "9.4"
before_install:
  # Use default port
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/9.4/main/postgresql.conf
before_script:
  - psql -U postgres -c "CREATE DATABASE VaidBike;"
jdk:
  - oraclejdk8
