sudo: false
language: java
install: true
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean package
services:
    - postgresql
addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-9.3
      - postgresql-client-9.3
before_script:
  - "cp ./.travis.database.yml ./config/database.yml"
jdk:
  - oraclejdk8
