language: java
sudo: false
services:
  - postgresql
before_install:
  - psql -c 'create database VaidBike;' -U postgres
addons:
  postgresql: "9.3"
cache:
  directories:
    - "$HOME/.m2"
jdk:
  - oraclejdk8
script:
  - set -e
  - mvn clean package

