sudo: false
language: java
cache:
  directories:
    - $HOME/.m2
script:
  - mvn install
  - set -e
  - mvn clean package
services:
    - postgresql
addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-9.3
      - postgresql-client-9.3
before_script:
  - psql -c 'create database VaidBike;' -U postgres
jdk:
  - oraclejdk8
